run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - gosec
    - revive
    - stylecheck
    - unparam
    - nakedret
    - prealloc
    - exportloopref
  disable:
    - structcheck
    - varcheck
    - deadcode

linters-settings:
  gocyclo:
    min-complexity: 15
  
  gosec:
    severity: medium
    confidence: medium
  
  revive:
    min-confidence: 0.8
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  misspell:
    locale: US
    
  nakedret:
    max-func-lines: 30

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: cmd/
      linters:
        - gocyclo
    - text: "weak cryptographic primitive"
      linters:
        - gosec
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true