linters:
  enable:
    - gofmt
    - govet
    - revive
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - goimports
    - misspell
    - lll
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
    excludes:
      - G505 # 忽略 SHA-1 检查（微信 API 可能需要）

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - lll
        - goconst
    - path: internal/service/wechat/token.go
      linters:
        - gosec
      text: "G505" # 针对 token.go 的 SHA-1 忽略（可选）
    - path: internal/service/wechat/.+\.go
      linters:
        - gosec
      text: "G107" # 忽略微信服务中的变量 URL 检查（确认安全）
    - path: internal/model/response.go
      linters:
        - gosec
      text: "G101" # 忽略 response.go 的硬编码凭据误报
  exclude-dirs:
    - vendor/

run:
  deadline: 5m
  tests: true

output:
  formats:
    - format: colored-line-number # 更新为新格式
